### ISSUE TITLE
move config.json outside of container

### ISSUE THREAD

**Issue by snizzleorg** [patrickbusch/homebridge-docker#2]
wouldn't it be a good idea to move the config.son out of the container so that the config could be modified without rebuilding the container?

**Comment by patrickbusch** [comment]
yes, this is the logical next step. unfortunately I'm not able to do this this month - would you want to try?

**Comment by snizzleorg** [comment]
i will try this week if i find the time.

**Comment by snizzleorg** [comment]
I tried but unfortunately it's not working for me. The container exits right away - problem is sing eat exits right way I do not know how to get to the logs...

**Comment by snizzleorg** [comment]
... ok I had a problem in the config.json file. Now everything works beautifully.

**Comment by snizzleorg** [comment]
closed as this is now working nicely
